### ISSUE TITLE
📅 - Migrate old Meet URLs

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/discovery#119]
New Calendar
https://calendar.google.com/calendar/u/0/embed?src=null@scrf.io&ctz=America/Los_Angeles

### Benefit to SCRF
Currently, there are meeting links being used that are hosted on the old SCRF domain. In order to allow @scrf.io accounts to record and manage these hosted events they need to be re-created by the null@scrf.io account and placed on the above calendar.

### Events
All events listed in the [SCRF Calendar of Events](https://github.com/orgs/smartcontractresearchforum/projects/30) PB

### Tasks
- [x] generate new Meet URLs for each calendar event
- [x] remove old meeting links from the current calendar
- [x] Ensure all the files in the docs repo updated with new URLs.
- [x] Update all links in Discovery repo calendar issues
- [x] Update native events listed in Discord with new URLs
- [x] Update sesh bot with new URLs

### Managing Events

For reference, events are managed in the [SCRF Calendar of Events](https://github.com/orgs/smartcontractresearchforum/projects/30) PB

New events can be submitted here:
[Discovery Repo New Issue](https://github.com/smartcontractresearchforum/discovery/issues/new/choose) `📅 Add New Calendar Event`
