### ISSUE TITLE
Visual Brand Design MVP

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#135]
Description: As Discovery, we want to have meaningful, consistent, and engaging brand design so that people can recognize visually who we are and what we do. The MVP version of our brand design includes the initial brand guide, logo, typography, and color palette.
- Without visual brand design, people will use and create their own leading to inconsistency and confusing values
- Without meaningful design, people are left to interpret our narratives and visuals for themselves. 

Issues/ Tasks:
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/33
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/34
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/35
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/32
