### ISSUE TITLE
Visual Brand Design v1

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#136]
Description: SCRF has the MVP version of the brand guide and related assets. Now we expand imagery, patterns, and templates.

- [x]  https://github.com/smartcontractresearchforum/discovery/issues/47
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/70
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/37
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/57
- [x]  https://github.com/smartcontractresearchforum/discovery/issues/36
