### ISSUE TITLE
📅 - Rename Community Calls

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/discovery#158]
### Event Name

Community calls

### Change

I would like to step away from regional naming of the calls to either calls 1 and 2 or some other distinction. Especially as the timezones are pretty close now, the regional distinction feels very arbitrary (especially as it doesn't cover all relevant regions by timezone)

### Tasks
- [x] Rename the following events:
Community Call: EU and APAC ➡️ `Monday Community Call`
Community Call: Americas ➡️ `Thursday Community Call`

- [x] Update issues in PB
- [x] Update GCal
- [x] Update Sesh
- [x] Update Discord Events

**Comment by SirAh0** [comment]
How about `Monday Community Call` and `Thursday Community Call`

**Comment by SirAh0** [comment]
all events updated
