### ISSUE TITLE
(Meta) Streamline Docs Project Board

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#16]
- [ ] Populate the Board with all documentation.
- [ ] #21
- [ ] Incorporate signees and approvers to the process.
- [ ] Flesh out the Process Phases to track each step from draft to published.

**Comment by vsterling** [comment]
This issue is now under the Discovery project board: https://github.com/orgs/smartcontractresearchforum/projects/17/views/1
