### ISSUE TITLE
SCRF.io - Soft Launch

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/discovery#163]
### Initial SCRF.io Launch
A single page with static content. 

### Tasks

- [ ] develop wireframes and basic UI/UX @SirAh0 @marvino3 
- [ ] Copy and imagery will then flow into the wireframes. @marvino3 

- [ ] Designer to provide full design for desktop view.  @MattDesigner 

- [ ] implement the full design as a functioning responsive webpage. @SirAh0 

### Links

[SCRF.io Technical Specs](https://docs.google.com/document/d/1VyXvDChESbrDQMKZK3ouzJqEz5v0MyOnZIRqFdYrSZw/edit#heading=h.catud88umh40)

[SCRF.io Project Plan](https://docs.google.com/document/d/13o9cY3TOr9T3rKg3qcHHECnQqiTo8Vz2pfOVMNoHjdk/edit#heading=h.o6430bqtn89k)

[SCRF.io Homepage Wireframe](https://www.figma.com/file/iBYT9jpztaldLVQdf1xxxW/SCRF.io-Home-Page-Wireframe?node-id=0%3A1)
