### ISSUE TITLE
(Meta) Restructure Docs Repo

### ISSUE THREAD

**Issue by vsterling** [smartcontractresearchforum/discovery#19]
- [x] Meet with Engagement, Onboarding, and Content Teams and @marvino3 
- [ ] Make changes on the Test docs repo
- [ ] Update READ ME and repo folder structure

Key Docs:
[GitHub ReadMe [UPDATE]](https://docs.google.com/document/d/1CJDTt9BL5OeEWKOPQ6IzbhtNAjxZbRlHOfuN-L0qkMQ/edit?usp=sharing)
[GitHub ToC Planning Doc](https://docs.google.com/document/d/1VvSFpQDKAIHxxbOo2WXjQvujX8EQgF4YOQJAdW3fFN0/edit?usp=sharing)

**Comment by vsterling** [comment]
- Garnered feedback with Onboarding and Content teams
- Created an updated version [GitHub ReadMe [UPDATE]](https://docs.google.com/document/d/1CJDTt9BL5OeEWKOPQ6IzbhtNAjxZbRlHOfuN-L0qkMQ/edit?usp=sharing)
- Just got added to the docs test repo to implement changes

**Comment by vsterling** [comment]
This issue is now being tracked on the Discovery project board as [issue #120](https://github.com/smartcontractresearchforum/discovery/issues/120).
