### ISSUE TITLE
Updating the Socials Project Plan

### ISSUE THREAD

**Issue by marvino3** [smartcontractresearchforum/discovery#84]
[Project Proposal Template](https://docs.google.com/document/d/1kBN2XUfghk1Rk27oNioBm4uxxap7N_8d8WCMS6lkYIo/edit#)

[Social Media Strategy](https://docs.google.com/document/d/1Vjrk7u7HPhXPi9hywFRN5Cq6dnK3yIyce8i8FeLoVEo/edit#heading=h.ij804l6z2vm3)

[Youtube Strategy](https://docs.google.com/document/d/1uiD0KF7orMsw2w_Vyl6Oif3KX5BCOeEHTGH2biKvSB4/edit#)

**Comment by marvino3** [comment]
- [ ] Update Socials Project Plan @MichaelSCRF 
- [ ] Review with @marvino3 
- [ ] Finalize and Upload to GitHub @vsterling

**Comment by MichaelSCRF** [comment]
[Here](https://docs.google.com/document/d/1suoQtgnJpA4LqahyPYpTy4_qCEw_7hEWZahgMrnx6YM/edit#heading=h.9xvwuxmfaxqg) is the updated Socials Project Plan in the updated Project Proposal Template

**Comment by MichaelSCRF** [comment]
@MichaelSCRF - take a last pass, look at notes and incorporate changes

**Comment by MichaelSCRF** [comment]
@marvino3 - changes incorporated!

**Comment by marvino3** [comment]
@MichaelSCRF please link the latest Socials Project Plan doc

**Comment by MichaelSCRF** [comment]
@marvino3, here is the latest version of the Socials Project Plan: https://docs.google.com/document/d/1suoQtgnJpA4LqahyPYpTy4_qCEw_7hEWZahgMrnx6YM/edit#heading=h.9xvwuxmfaxqg
